import TopNav from "@/component/navbar/TopNav";
import "./globals.css";
import { Providers } from "@/component/Providers";
export const metadata = {
  title: "NextMatch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav />
          <main className="container mx-auto ">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
