import TopNav from "@/components/navbar/TopNav";
import "./globals.css";
import Providers from "@/herouiProvider/Providers";

export const metadata = {
  title: "NextMatch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav />
          <main className="container mx-auto p-10">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
